Controllers/ResourceManagementController.cs
#region System
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using viramesV4.Cloud.Helpers;
using viramesV4.Object.BusinessLogicLayer.Master;
using viramesV4.Object.BusinessLogicLayer.System;
using viramesV4.Object.Factory;
using viramesV4.Object.HelperLayer;
namespace viramesV4.Cloud.Controllers
#endregion
{ 
    [ViramesAuthorization]
    public class ResourceManagementController : Controller
    {

        #region Master Records
        #region workstationGroup
        public ActionResult WorkstationGroup()
        {
            ViewBag.Isactive = 41;
            List<WorkstationGroup> WorkstationGroupList = virames<WorkstationGroup>
                             .Initialize(new List<WorkstationGroup>())
                              .GetList();
            return View(WorkstationGroupList);
        }
        [HttpGet]
        public ActionResult NewWorkstationGroup()
        {

            WorkstationGroup workstationGroup = new WorkstationGroup();
            return View(workstationGroup);
        }
        [HttpPost]
        public ActionResult NewWorkstationGroup(WorkstationGroup workstationGroup)
        {

            workstationGroup.Save();
            return RedirectToAction("WorkstationGroup");
        }
        [HttpGet]
        public ActionResult EditWorkstationGroup(int ID)
        {
            ViewBag.RecordStatus = new SelectList(Enum.GetValues(typeof(RecordStatus)));
            WorkstationGroup workstationGroup = virames<WorkstationGroup>
                             .Initialize(new WorkstationGroup()).Where(x => x.ID.ToString() == ID.ToString())
                             .Take();
            return View(workstationGroup);
        }
        [HttpPost]
        public ActionResult EditWorkstationGroup(WorkstationGroup workstationGroup)
        {

            workstationGroup.Save();
            return RedirectToAction("WorkstationGroup");
        }
        [HttpGet]
        public ActionResult DetailWorkstationGroup(int ID)
        {
            WorkstationGroup workstationGroup = virames<WorkstationGroup>
                            .Initialize(new WorkstationGroup()).Where(x => x.ID.ToString() == ID.ToString())
                            .Take();
            return View(workstationGroup);
        }
        [HttpPost]
        public ActionResult DetailWorkstationGroup(WorkstationGroup workstationGroup)
        {
            workstationGroup.Save();
            return RedirectToAction("WorkstationGroup");
        }
        [HttpGet]
        public ActionResult DeleteWorkstationGroup(int ID)
        {
            WorkstationGroup workstationGroup = virames<WorkstationGroup>
                           .Initialize(new WorkstationGroup()).Where(x => x.ID.ToString() == ID.ToString())
                           .Take();
            return View(workstationGroup);

        }
        [HttpPost]
        public ActionResult DeleteWorkstationGroup(WorkstationGroup workstationGroup)
        {
            workstationGroup.Delete();
            return RedirectToAction("WorkstationGroup");
        }
        [HttpGet]
        public ActionResult WorkstationGroupWorkstationAppointmentAssigned(int ID)
        {
            List<Workstation> workstationGroupWorkstationAppointmentAssigned = virames<WorkstationGroupWorkstationAppointment>
                             .Initialize(new List<WorkstationGroupWorkstationAppointment>())
                             .Where(x => x.WorkstationGroupID == ID)
                            .GetList().Select(x => x.Workstation).ToList();
            return View(workstationGroupWorkstationAppointmentAssigned);
        }
        [HttpGet]
        public ActionResult EmployeeWorkstationGroupAppointmentAssigned(int ID)
        {
            List<Employee> employees = virames<EmployeeWorkstationGroupAppointment>
                            .Initialize(new List<EmployeeWorkstationGroupAppointment>())
                            .Where(x => x.WorkstationGroupID == ID)
                            .GetList().Select(x => x.Employee).ToList();
            return View(employees);
        }
        [HttpGet]
        public ActionResult DocumentWorkstationGroupAppointmentAssigned(int ID)
        {
            List<Document> document = virames<DocumentWorkstationGroupAppointment>
                             .Initialize(new List<DocumentWorkstationGroupAppointment>())
                              .Where(x => x.WorkstationGroupID == ID)
                             .GetList().Select(x => x.Document).ToList();
            return View(document);
        }
        #endregion

        #region workstation
        public ActionResult Workstations()
        {
            ViewBag.Isactive = 43;
            List<Workstation> workstationList = virames<Workstation>
                             .Initialize(new List<Workstation>())
                             .GetList();
            return View(workstationList);
        }
        [HttpGet]
        public ActionResult EditWorkstation(int ID)
        {
            ViewBag.RecordStatus = new SelectList(Enum.GetValues(typeof(RecordStatus)));
            Workstation workstation = virames<Workstation>
                             .Initialize(new Workstation()).Where(x => x.ID.ToString() == ID.ToString())
                             .Take();
            return View(workstation);
        }
        [HttpPost]
        public ActionResult EditWorkstation(Workstation workstation)
        {
            workstation.Save();
            return RedirectToAction("Workstations");
        }
        [HttpGet]
        public ActionResult DetailWorkstations(int ID)
        {
            Workstation workstation = virames<Workstation>
                            .Initialize(new Workstation()).Where(x => x.ID.ToString() == ID.ToString())
                            .Take();
            return View(workstation);
        }
        [HttpPost]
        public ActionResult DetailWorkstations(Workstation workstation)
        {
            workstation.Save();
            return RedirectToAction("Workstations");
        }
        [HttpGet]
        public ActionResult DeleteWorkstations(int ID)
        {
            Workstation workstation = virames<Workstation>
                           .Initialize(new Workstation()).Where(x => x.ID.ToString() == ID.ToString())
                           .Take();
            return View(workstation);

        }
        [HttpPost]
        public ActionResult DeleteWorkstations(Workstation workstation)
        {
            RealEstate realEstate = virames<RealEstate>
                           .Initialize(new RealEstate()).Where(x => x.ID == workstation.ID)
                           .Take();
            if (realEstate != null)
                realEstate.Delete();
            workstation.Delete();
            return RedirectToAction("Workstations");
        }
        [HttpGet]
        public ActionResult EmployeeWorkstationAppointmentAssigneds(int ID)
        {
            List<Employee> employees = virames<EmployeeWorkstationAppointment>
                            .Initialize(new List<EmployeeWorkstationAppointment>())
                            .Where(x => x.WorkstationID == ID)
                            .GetList().Select(x => x.Employee).ToList();
            return View(employees);
        }
        [HttpGet]
        public ActionResult DocumentWorkstationAppointmentAssigneds(int ID)
        {
            List<Document> document = virames<DocumentWorkstationAppointment>
                             .Initialize(new List<DocumentWorkstationAppointment>())
                              .Where(x => x.WorkstationID == ID)
                             .GetList().Select(x => x.Document).ToList();
            return View(document);
        }
        #endregion

        #region employee
        public ActionResult Employee()
        {
            ViewBag.Isactive = 44;
            List<Employee> EmployeeList = virames<Employee>
                             .Initialize(new List<Employee>())
                             .GetList();
            return View(EmployeeList);
        }
        [HttpGet]
        public ActionResult NewEmployee()
        {
            ViewBag.DepartmentScope = virames<Department>
                          .Initialize(new List<Department>())
                          .GetList().Select(x => new SelectListItem
                          {
                              Value = x.ID.ToString(),
                              Text = "Kod = " + x.Code + " | " + "Tanım = " + x.Definition
                          });
            ViewBag.EmployeeType = new SelectList(Enum.GetValues(typeof(EmployeeType)));
            ViewBag.MaritalStatus = new SelectList(Enum.GetValues(typeof(MaritalStatus)));
            ViewBag.EducationLevel = new SelectList(Enum.GetValues(typeof(EducationLevel)));
            ViewBag.Gender = new SelectList(Enum.GetValues(typeof(Gender)));
            Employee employee = new Employee();
            return View(employee);
        }
        [HttpPost]
        public ActionResult NewEmployee(Employee employee)
        {

            employee.Save();
            return RedirectToAction("Employee");
        }
        [HttpGet]
        public ActionResult EditEmployees(int ID)
        {
            ViewBag.MaritalStatus = new SelectList(Enum.GetValues(typeof(MaritalStatus)));
            ViewBag.EducationLevel = new SelectList(Enum.GetValues(typeof(EducationLevel)));
            ViewBag.Gender = new SelectList(Enum.GetValues(typeof(Gender)));
            ViewBag.RecordStatus = new SelectList(Enum.GetValues(typeof(RecordStatus)));
            ViewBag.DepartmentScope = virames<Department>
                             .Initialize(new List<Department>())
                             .GetList().Select(x => new SelectListItem
                             {
                                 Value = x.ID.ToString(),

Views/ResourceManagement/CertificateList.cshtml
@using viramesV4.Object.BusinessLogicLayer.Master
@model IList<Certificate>
@{
    ViewBag.Title = "certificateList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h3>Belge Kartları</h3>
    <div class="box-body">
        <a class="btn btn-app btn btn-primary" href="~/ResourceManagement/NewCertificatee">
            <i class="fa fa-file"></i> Yeni
        </a>
        <a class="btn btn-app">
            <i class="fa fa-share-square" data-toggle="modal" data-target="#ModalButton"></i> Aktarım
        </a>
        <div class="modal fade" id="ModalButton" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h3>Dışa Aktar</h3>
                    </div>
                    <div class="modal-body">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                            <label class="form-check-label" for="inlineRadio1">Text File (.txt)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                            <label class="form-check-label" for="inlineRadio2">Excel File (.xlsx)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                            <label class="form-check-label" for="inlineRadio1">Html File (.txt)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="option4">
                            <label class="form-check-label" for="inlineRadio2">PDF File (.pdf)</label>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Aktar</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Kapat</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> 

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Sertifika Kodu</th>
                                <th>Sertifika Tanımı</th>
                                <th>Durum</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Certificate certificate in Model)
                            {
                            <tr>
                                <td>@certificate.Code</td>
                                <td>@certificate.Definition</td>
                                <td>@certificate.Status</td>
                                <td>
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Seç
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="@Url.Action("DetailCertificatee", "ResourceManagement", new { id = certificate.ID })"><span class="fa fa-eye"> Görüntüle </span></a> <br />
                                            <a href="@Url.Action("EditCertificatee", "ResourceManagement", new { id = certificate.ID })"><span class="fa fa-edit"> Düzenle </span></a> <br />
                                            <a href="@Url.Action("DeleteCertificatee", "ResourceManagement", new { id = certificate.ID })"><span class="fa fa-trash"> Sil </span></a> <br />
                                            <a href="@Url.Action("DocumentCertificateAppointmentAssigneds", "ResourceManagement", new { id = certificate.ID })"><span class="fa fa-sitemap"> D.Yönetimi </span></a> <br />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

Views/ResourceManagement/DeleteCertificatee.cshtml
@model viramesV4.Object.BusinessLogicLayer.Master.Certificate

@{
    ViewBag.Title = "deleteCertificate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <section class="content-header">
        <h3>Sertifika Tanımları</h3>
        <div class="box-body ">
            <a class="btn btn-app btn btn-primary" onclick="goBack()">
                <i class="fa fa-arrow-left"></i> Geri
            </a>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Sil</h3>
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Code)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Code)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Definition)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Definition)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CodeAndDefinition)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CodeAndDefinition)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CreatedBy)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CreatedBy)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CreatedDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CreatedDate)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ModifiedBy)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ModifiedBy)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ModifiedDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ModifiedDate)
                                </dd>

                            </dl>
                        </div>
                        <br />
                        <div class="form-actions col-xs-2">
                            <input type="submit" value="Sil" class="btn btn-app btn btn-primary" />
                        </div>
                        <br />
                        <br />
                        <br />
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </section>

}

Views/ResourceManagement/DeleteDepartment.cshtml
@model viramesV4.Object.BusinessLogicLayer.Master.Department

@{
    ViewBag.Title = "deleteDepartment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <section class="content-header">
        <h3>Departman Tanımları</h3>
        <div class="box-body ">
            <a class="btn btn-app btn btn-primary" onclick="goBack()">
                <i class="fa fa-arrow-left"></i> Geri
            </a>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Sil</h3>
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Code)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Code)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Definition)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Definition)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CodeAndDefinition)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CodeAndDefinition)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ResponsibleEmployee)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ResponsibleEmployee)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.UpperDepartment)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.UpperDepartment)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Level)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Level)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CreatedBy)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CreatedBy)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CreatedDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CreatedDate)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ModifiedBy)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ModifiedBy)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ModifiedDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ModifiedDate)
                                </dd>

                            </dl>
                        </div>
                    </div>
                    <br />
                    <div class="form-actions col-xs-2">
                        <input type="submit" value="Sil" class="btn btn-app btn btn-primary" />
                    </div>
                    <br />
                    <br />
                    <br />
                    <br />
                </div>
            </div>
        </div>
    </section>

}

Views/ResourceManagement/DeleteLocation.cshtml
@model viramesV4.Object.BusinessLogicLayer.Master.Location

@{
    ViewBag.Title = "deleteLocation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <section class="content-header">
        <h3>Konum Tanımları</h3>
        <div class="box-body ">
            <a class="btn btn-app btn btn-primary" onclick="goBack()">
                <i class="fa fa-arrow-left"></i> Geri
            </a>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Sil</h3>
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.AddressOrLocation)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.AddressOrLocation)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CreatedBy)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CreatedBy)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CreatedDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CreatedDate)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ModifiedBy)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ModifiedBy)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ModifiedDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ModifiedDate)
                                </dd>

                            </dl>
                        </div>
                        <br />
                        <div class="form-actions col-xs-2">
                            <input type="submit" value="Sil" class="btn btn-app btn btn-primary" />
                        </div>
                        <br />
                        <br />
                        <br />
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </section>

}

Views/ResourceManagement/WorkstationGroupWorkstationAppointmentAssigned.cshtml
@using viramesV4.Object.BusinessLogicLayer.Master
@model IList<Workstation>

@{
    ViewBag.Title = "workstationGroupWorkstationAppointmentAssigned";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h3>İş İstasyonu Tanımları</h3>
    <div class="box-body ">
        <a class="btn btn-app btn btn-primary" onclick="goBack()">
            <i class="fa fa-arrow-left"></i> Geri
        </a>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">İş İstasyonu Havuzuna Atanmış İş İstasyonları</h3>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>İş İstasyonu Kodu</th>
                                <th>İş İstasyonu Tanımı</th>
                                <th>Konum</th>
                                <th>Tarih Periyodik Bakımı</th>
                                <th>Periyodik Bakım Sayısı</th>
                                <th>İş İstasyonu Durumu</th>
                                <th>Gerçekleşen Son Periyodik Bakım Tarihi</th>
                                <th>Mevcut Periyodik Bakım Sayısı</th>
                                <th>Gerçekleşen Son P.Bakım Tarihi</th>
                                <th>Düzenle</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Workstation workstation in Model)
                            {
                            <tr>
                                <td>@workstation.Code</td>
                                <td>@workstation.Definition</td>
                                <td>@workstation.Location</td>
                                <td>
                                    @if (workstation.DatePeriodicMaintenance == true)
                                    {
                                        <input type="checkbox" checked />
                                    }
                                    @if (workstation.DatePeriodicMaintenance == false)
                                    {
                                        <input type="checkbox" />
                                    }
                                </td>
                                <td>
                                    @if (workstation.CountPeriodicMaintenance == true)
                                    {
                                        <input type="checkbox" checked />
                                    }
                                    @if (workstation.CountPeriodicMaintenance == false)
                                    {
                                        <input type="checkbox" />
                                    }
                                </td>
                                <td>@workstation.Status</td>
                                <td>@workstation.LastPeriodicMaintenanceDate</td>
                                <td>@workstation.CurrentPeriodicMaintanceCount</td>
                                <td>@workstation.AmortizationYear</td>
                                <td>
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Seç
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="@Url.Action("DetailWorkstation", "ResourceManagement", new { id = workstation.ID })"><span class="fa fa-eye"> Görüntüle </span></a> <br />
                                            <a href="@Url.Action("EditWorkstation", "ResourceManagement", new { id = workstation.ID })"><span class="fa fa-edit"> Düzenle </span></a> <br />
                                        </div>

                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>