Controllers/ProductionPlanningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using viramesV4.Cloud.Helpers;
using viramesV4.Object.BusinessLogicLayer.Master;
using viramesV4.Object.BusinessLogicLayer.System;
using viramesV4.Object.Factory;
using viramesV4.Object.HelperLayer;

namespace viramesV4.Cloud.Controllers
{
    [ViramesAuthorization]
    public class ProductionPlanningController : Controller
    {
        #region shiftDefinitions
        // GET: ProductionPlanning
        public ActionResult shiftDefinitions()
        {
            ViewBag.Isactive = 21;
            List<Shift> shiftDefinitionList = virames<Shift>.Initialize(new List<Shift>()).GetList();
            return View(shiftDefinitionList);
        }
        #region detail 
        [HttpGet]
        public ActionResult detailShiftDefinition(int ID)
        {

            Shift shiftDefinition = virames<Shift>
                            .Initialize(new Shift()).Where(x => x.ID.ToString() == ID.ToString())
                            .Take();
            return View(shiftDefinition);
        }
        [HttpPost]
        public ActionResult detailShiftDefinition(Shift shiftDefinition)
        {
            shiftDefinition.Save();
            return RedirectToAction("shiftDefinitions");
        }
        #endregion
        #region new
        [HttpGet]
        public ActionResult newShiftDefinition()
        {

            Shift shiftDefinition = new Shift();
            return View(shiftDefinition);
        }
        [HttpPost]
        public ActionResult newShiftDefinition(Shift shiftDefinition)
        {
            shiftDefinition.Save();
            return RedirectToAction("shiftDefinitions");
        }
        #endregion
        #region edit
        [HttpGet]
        public ActionResult editShiftDefinition(int ID)
        {

            Shift shiftDefinition = virames<Shift>
                             .Initialize(new Shift()).Where(x => x.ID.ToString() == ID.ToString())
                             .Take();
            ViewBag.ShiftDefinition = shiftDefinition;
            return View(shiftDefinition);
        }
        [HttpPost]
        public ActionResult editShiftDefinition(Shift shiftDefinition)
        {
            shiftDefinition.Save();
            return RedirectToAction("shiftDefinitions");
        }
        #endregion
        #region delete
        [HttpGet]
        public ActionResult deleteShiftDefinition(int ID)
        {
            Shift shiftDefinition = virames<Shift>
                           .Initialize(new Shift()).Where(x => x.ID.ToString() == ID.ToString())
                           .Take();
            return View(shiftDefinition);

        }
        [HttpPost]
        public ActionResult deleteShiftDefinition(Shift shiftDefinition)
        {
            shiftDefinition.Delete();
            return RedirectToAction("shiftDefinitions");
        }
        #endregion
        #endregion

        #region interruptionTypeDefinition
        public ActionResult interruptionTypeDefinition()
        {
            ViewBag.Isactive = 22;
            List<Interruption> interruptionTypeDefinitionList = virames<Interruption>.Initialize(new List<Interruption>()).GetList();
            return View(interruptionTypeDefinitionList);
        }
        #region new
        [HttpGet]
        public ActionResult newinterruptionTypeDefinition()
        {

            Interruption interruption = new Interruption();
            return View(interruption);
        }
        [HttpPost]
        public ActionResult newinterruptionTypeDefinition(Interruption interruption)
        {
            interruption.Save();
            return RedirectToAction("interruptionTypeDefinition");
        }
        #endregion
        #region detail
        [HttpGet]
        public ActionResult detailinterruptionTypeDefinition(int ID)
        {

            Interruption interruption = virames<Interruption>
                            .Initialize(new Interruption()).Where(x => x.ID.ToString() == ID.ToString())
                            .Take();
            return View(interruption);
        }
        [HttpPost]
        public ActionResult detailinterruptionTypeDefinition(Interruption interruption)
        {
            interruption.Save();
            return RedirectToAction("interruptionTypeDefinition");
        }
        #endregion
        #region edit
        [HttpGet]
        public ActionResult editinterruptionTypeDefinition(int ID)
        {

            Interruption interruption = virames<Interruption>
                             .Initialize(new Interruption()).Where(x => x.ID.ToString() == ID.ToString())
                             .Take();
            ViewBag.Interruption = interruption;
            return View(interruption);
        }
        [HttpPost]
        public ActionResult editinterruptionTypeDefinition(Interruption interruption)
        {
            interruption.Save();
            return RedirectToAction("interruptionTypeDefinition");
        }
        #endregion
        #region delete
        [HttpGet]
        public ActionResult deleteinterruptionTypeDefinition(int ID)
        {
            Interruption interruption = virames<Interruption>
                           .Initialize(new Interruption()).Where(x => x.ID.ToString() == ID.ToString())
                           .Take();
            return View(interruption);

        }
        [HttpPost]
        public ActionResult deleteinterruptionTypeDefinition(Interruption interruption)
        {
            interruption.Delete();
            return RedirectToAction("interruptionTypeDefinition");
        }
        #endregion
        #endregion

        #region bomDefinitions
        public ActionResult bomDefinitions()
        {
            ViewBag.Isactive = 23;
            List<BOM> bomList = virames<BOM>.Initialize(new List<BOM>()).GetList();
            return View(bomList);
        }
        #region new
        [HttpGet]
        public ActionResult newBOMDefinition()
        {
            ViewBag.Warehouse = virames<Warehouse>.Initialize(new List<Warehouse>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.Code + " | " + x.WarehouseName
            });
            ViewBag.Workstation = virames<Workstation>.Initialize(new List<Workstation>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.ID + " | " + x.Code + " | " + x.Definition
            });
            ViewBag.Material = virames<Material>.Initialize(new List<Material>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.ID + " | " + x.MaterialType + " | " + x.Code + " | " + x.Definition
            });
            ViewBag.SpeCode = virames<SpeCode>.Initialize(new List<SpeCode>()).Where(x => x.SpeCodeType == SpeCodeType.BOM).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.SpecialCode + " | " + x.SpeCodeType
            });

            BOM bom = new BOM();
            return View(bom);
        }
        [HttpPost]
        public ActionResult newBOMDefinition(BOM bom)
        {
          //  bom.Save();
            return RedirectToAction("bomDefinitions");
        }
        #endregion
        #region detail
        [HttpGet]
        public ActionResult detailBOMDefinition(int ID)
        {
            ViewBag.Warehouse = virames<Warehouse>.Initialize(new List<Warehouse>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.Code + " | " + x.WarehouseName
            });
            ViewBag.Workstation = virames<Workstation>.Initialize(new List<Workstation>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.ID + " | " + x.Code + " | " + x.Definition
            });
            ViewBag.Material = virames<Material>.Initialize(new List<Material>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.ID + " | " + x.MaterialType + " | " + x.Code + " | " + x.Definition
            });
            ViewBag.SpeCode = virames<SpeCode>.Initialize(new List<SpeCode>()).Where(x => x.SpeCodeType == SpeCodeType.BOM).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.SpecialCode + " | " + x.SpeCodeType
            });

            BOM bom = virames<BOM>
                            .Initialize(new BOM()).Where(x => x.ID.ToString() == ID.ToString())
                            .Take();
            return View(bom);
        }
        [HttpPost]
        public ActionResult detailBOMDefinition(BOM bom)
        {
          //  bom.Save();
            return RedirectToAction("bomDefinitions");
        }
        #endregion
        #region edit
        [HttpGet]
        public ActionResult editBOMDefinition(int ID)
        {

            ViewBag.Warehouse = virames<Warehouse>.Initialize(new List<Warehouse>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.Code + " | " + x.WarehouseName
            });
            ViewBag.Workstation = virames<Workstation>.Initialize(new List<Workstation>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.ID + " | " + x.Code + " | " + x.Definition
            });
            ViewBag.Material = virames<Material>.Initialize(new List<Material>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.ID + " | " + x.MaterialType + " | " + x.Code + " | " + x.Definition
            });

Views/ProductionPlanning/productionOrders.cshtml
@{
    ViewBag.Title = "productionOrders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using viramesV4.Object.BusinessLogicLayer.Master
@model IList<ProductOrder>


<section class="content-header">
    <h1>
       Üretim Emri Tanımları

    </h1>

    <div class="box-body">

        <a href="http://virames.cloud/ProductionPlanning/newProductOrder" class="btn btn-app btn btn-primary">
            <i class="fa fa-file"></i> Yeni
        </a>


        <a class="btn btn-app">
            <i class="fa fa-share-square"></i>Aktarım
        </a>

    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">

        <div class="col-xs-12">



            <!-- /.box -->

            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Numara</th>
                                <th>Depo</th>
                                <th>Açıklama</th>
                                <th>Miktarı</th>
                                <th>Durum</th>
                                <th>Tamamlama</th>
                                <th>Tarih</th>
                                <th>Özel Kod</th>
                                <th>Ana Malzeme</th>
                                <th>Durum Planlaması</th>
                                <th>İşlem</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (ProductOrder productOrder in Model)
                            {

                            <tr>
                                <td>@productOrder.Number</td>
                                <td>@productOrder.Warehouse</td>
                                <td>@productOrder.DescriptionPreview</td>
                                <td>@productOrder.Amount</td>
                                <td>@productOrder.ProductOrderStatus</td>
                                <td>% @productOrder.Completion</td>
                                <td>@productOrder.Date</td>
                                <td>@productOrder.SpeCode</td>
                                <td>@productOrder.MainMaterial</td>
                                <td>@productOrder.PlanningStatus</td>
                                <td>
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Seç
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="@Url.Action("detailProductOrder", "ProductionPlanning", new { id = productOrder.ID })" ><span class="fa fa-eye"> Görüntüle </span></a> <br />
                                            <a href="@Url.Action("editProductOrder", "ProductionPlanning", new { id = productOrder.ID })"><span class="fa fa-edit"> Düzenle </span></a> <br />
                                            <a  href="#" onclick="javascript:deleteRow('@productOrder.ID', '@productOrder.Number');"  ><span class="fa fa-trash" > Sil </span></a> <br />
                                        </div>

                                    </div>
                                </td>
                            </tr>

                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Numara</th>
                                <th>Depo</th>
                                <th>Açıklama</th>
                                <th>Miktarı</th>
                                <th>Durum</th>
                                <th>Tanımlama</th>
                                <th>Tarih</th>
                                <th>Özel Kod</th>
                                <th>Ana Malzeme</th>
                                <th>Durum Planlaması</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

<script>
    function deleteRow(id, name) {
        swal({
            title: "Silmek istediğinize emin misiniz?",
            text: "\"" + name + "\" numaralı kayıtı silecek misiniz?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Sil",
            closeOnConfirm: false
         
        }, function () {
            swal("Silindi!", "İlgili kayıt silindi", "success");
            window.location.href = '/ProductionPlanning/deleteProductOrder/' + id;
            closeOnConfirm: true;

        });
    };
</script>

Views/ProductionPlanning/project.cshtml
@{
    ViewBag.Title = "project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using viramesV4.Object.BusinessLogicLayer.Master
@model IList<Project>


<section class="content-header">
  

   
        <div class="box-body">
            <a href="http://virames.cloud/ProductionPlanning/newProject" class="btn btn-app btn btn-primary">
                <i class="fa fa-file"></i> Yeni
            </a>
            <a class="btn btn-app">
                <i class="fa fa-share-square"></i>Aktarım
            </a>
        </div>


     


</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h2>
                        Proje Tanımları
                    </h2>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Proje Kodu</th>
                                <th>Proje Tanımı</th>
                                <th>Başlangıç Tarihi</th>
                                <th>Bitiş Tarihi</th>
                                <th>Özel Kod</th>
                                <th>İşlem</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Project project in Model)
                            {

                            <tr>
                                <td>@project.Code</td>
                                <td>@project.Definition</td>
                                <td>@project.StartDate</td>
                                <td>@project.EndDate</td>
                                <td>@project.SpeCode</td>
                                <td>
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Seç
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="@Url.Action("detailProject", "ProductionPlanning", new { id = project.ID })"><span class="fa fa-eye"> Görüntüle </span></a> <br />
                                            <a href="@Url.Action("editProject", "ProductionPlanning", new { id = project.ID })"><span class="fa fa-edit"> Düzenle </span></a> <br />
                                            <a href="@Url.Action("deleteProject", "ProductionPlanning", new { id = project.ID })"><span class="fa fa-trash"> Sil </span></a> <br />
                                            <a href="@Url.Action("detailProjectDocument", "ProductionPlanning", new { id = project.ID })"><span class="fa fa-sitemap"> Döküman Yönetimi </span></a> <br />
                                        </div>

                                    </div>
                                </td>
                            </tr>

                            }
                        </tbody>
                       
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

Views/ProductionPlanning/recipeSpecifiCodeDefinitions.cshtml
@{
    ViewBag.Title = "recipeSpecifiCodeDefinitions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using viramesV4.Object.BusinessLogicLayer.Master
@model IList<SpeCode>


<section class="content-header">
    <h1>
        Reçete Özel Kod İşlemleri

    </h1>

    <div class="box-body">
        <a href="http://virames.cloud/ProductionPlanning/newBOMSpeCode" class="btn btn-app btn btn-primary">
            <i class="fa fa-file"></i> Yeni
        </a>
        <a class="btn btn-app">
            <i class="fa fa-share-square"></i>Aktarım
        </a>

    </div>



</section>

<!-- Main content -->
<section class="content">
    <div class="row">

        <div class="col-xs-12">



            <!-- /.box -->

            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Özel Kod</th>
                                <th>Özel Kod Türü</th>
                                <th>Özel Kod Durumu</th>
                                <th>Yazı Rengi</th>
                                <th>Eğik Yazı</th>
                                <th>Kalın Yazı</th>
                                <th>Karakter Boyutu</th>
                                <th>Yazı Tipi Adı</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (SpeCode recipeSpeCode in Model)
                            {

                                <tr>
                                    <td>
                                        @if (recipeSpeCode.FontBold == false && recipeSpeCode.FontItalic == true)
                                        {
                                            <i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.SpecialCode</i>
                                        }
                                        else if (@recipeSpeCode.FontBold == true && @recipeSpeCode.FontItalic == false)
                                        {
                                            <strong><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.SpecialCode </strong>
                                        }
                                        else if (@recipeSpeCode.FontBold == true && @recipeSpeCode.FontItalic == true)
                                        {
                                            <strong><i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.SpecialCode</i></strong>
                                        }
                                        else
                                        {
                                            @recipeSpeCode.SpecialCode
                                        }
                                    </td>
                                    <td>
                                        @if (@recipeSpeCode.FontBold == false && @recipeSpeCode.FontItalic == true)
                                        {

                                            <i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.SpeCodeType</i>
                                        }
                                        else if (@recipeSpeCode.FontBold == true && @recipeSpeCode.FontItalic == false)
                                        {
                                            <b><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.SpeCodeType </b>
                                        }
                                        else if (@recipeSpeCode.FontBold == true && @recipeSpeCode.FontItalic == true)
                                        {
                                            <b><i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.SpeCodeType</i></b>
                                        }
                                        else
                                        {
                                            @recipeSpeCode.SpeCodeType
                                        }

                                    </td>
                                    <td>
                                        @if (@recipeSpeCode.FontItalic == true && @recipeSpeCode.FontBold == true)
                                        {
                                            <strong><i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.Status</i></strong>
                                        }
                                        else if (@recipeSpeCode.FontBold == true && @recipeSpeCode.FontItalic == false)
                                        {
                                            <strong> <p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.Status</strong>
                                        }
                                        else if (@recipeSpeCode.FontBold == false && @recipeSpeCode.FontItalic == true)
                                        {
                                            <i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.Status</i>
                                        }
                                        else
                                        {
                                            @recipeSpeCode.Status
                                        }
                                    </td>
                                    <td>
                                        @if (@recipeSpeCode.FontItalic == true && @recipeSpeCode.FontBold == true)
                                        {
                                            <strong><i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.FontColor</i></strong>
                                        }
                                        else if (@recipeSpeCode.FontBold == true && @recipeSpeCode.FontItalic == false)
                                        {
                                            <strong><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.FontColor</strong>
                                        }
                                        else if (@recipeSpeCode.FontBold == false && @recipeSpeCode.FontItalic == true)
                                        {
                                            <i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.FontColor</i>
                                        }
                                        else
                                        {
                                            @recipeSpeCode.FontColor
                                        }
                                    </td>
                                    <td>
                                        @if (@recipeSpeCode.FontItalic == true)
                                        {
                                            <input type="checkbox" value="" checked>
                                        }
                                        else
                                        {
                                            <input type="checkbox" value="">
                                        }
                                    </td>
                                    <td>
                                        @if (@recipeSpeCode.FontBold == true)
                                        {
                                            <input type="checkbox" value="" checked>
                                        }
                                        else
                                        {
                                            <input type="checkbox" value="">
                                        }

                                    </td>
                                    <td>
                                        @if (@recipeSpeCode.FontItalic == true && @recipeSpeCode.FontBold == true)
                                        {
                                            <strong><i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.FontSize</i></strong>
                                        }
                                        else if (@recipeSpeCode.FontBold == true && @recipeSpeCode.FontItalic == false)
                                        {
                                            <strong><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.FontSize</strong>
                                        }
                                        else if (@recipeSpeCode.FontBold == false && @recipeSpeCode.FontItalic == true)
                                        {
                                            <i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.FontSize</i>
                                        }
                                        else
                                        {
                                            @recipeSpeCode.FontSize
                                        }
                                    </td>
                                    <td>
                                        @if (@recipeSpeCode.FontItalic == true && @recipeSpeCode.FontBold == true)
                                        {
                                            <strong><i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.FontName</i></strong>
                                        }
                                        else if (@recipeSpeCode.FontBold == true && @recipeSpeCode.FontItalic == false)
                                        {
                                            <strong><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.FontName</strong>
                                        }
                                        else if (@recipeSpeCode.FontBold == false && @recipeSpeCode.FontItalic == true)
                                        {
                                            <i><p style="color: @recipeSpeCode.FontColor;">@recipeSpeCode.FontName</i>
                                        }
                                        else
                                        {
                                            @recipeSpeCode.FontName
                                        }
                                    </td>
                                    <td>
                                        <div class="dropdown btn-group dropleft">
                                            <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                                Seç
                                            </button>
                                            <div class="dropdown-menu">
                                                <a href="@Url.Action("detailBomSpeCode", "ProductionPlanning", new { id = recipeSpeCode.ID })"><span class="fa fa-eye"> Görüntüle </span></a> <br />
                                                <a href="@Url.Action("editBomSpeCode", "ProductionPlanning", new { id = recipeSpeCode.ID })"><span class="fa fa-edit"> Düzenle </span></a> <br />
                                                <a href="#" onclick="javascript:deleteRow('@recipeSpeCode.ID', '@recipeSpeCode.SpecialCode');"><span class="fa fa-trash"> Sil </span></a> <br />
                                            </div>

                                        </div>
                                    </td>
                                </tr>

                            }
                        </tbody>

                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<script>
    function deleteRow(id, name) {
        swal({
            title: "Silmek istediğinize emin misiniz?",
            text: "\"" + name + "\" özel kodlu kayıtı silecek misiniz?",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Sil",
            closeOnConfirm: false

        }, function () {
            swal("Silindi!", "İlgili kayıt silindi", "success");
            window.location.href = '/ProductionPlanning/deleteBomSpeCode/' + id;
            closeOnConfirm: true;

        });
    };
</script>