Controllers/ProductManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using viramesV4.Cloud.Helpers;
using viramesV4.Object.BusinessLogicLayer.Master;
using viramesV4.Object.BusinessLogicLayer.System;
using viramesV4.Object.Factory;
using viramesV4.Object.HelperLayer;

namespace viramesV4.Cloud.Controllers
{
    [ViramesAuthorization]
    public class ProductManagementController : Controller
    {
        #region MaterialDefinition
        public ActionResult materialDefinitions()
        {
           ViewBag.Isactive = 1;
            List<Material> materialList = virames<Material>.Initialize(new List<Material>()).GetList();
            return View(materialList);
        }
        [HttpGet]
        public ActionResult detailMaterialDefinition(int ID)
        {
            Material material = virames<Material>
                            .Initialize(new Material()).Where(x => x.ID.ToString() == ID.ToString())
                            .Take();
            return View(material);
        }
        [HttpPost]
        public ActionResult detailMaterialDefinition(Material material)
        {
            material.Save();
            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult editMaterialDefinition(int ID)
        {
            ViewBag.RecordStatus = new SelectList(Enum.GetValues(typeof(RecordStatus)));

            Material material = virames<Material>
                             .Initialize(new Material()).Where(x => x.ID.ToString() == ID.ToString())
                             .Take();
            ViewBag.Material = material;
            return View(material);
        }
        [HttpPost]
        public ActionResult editMaterialDefinition(Material material)
        {
            material.Save();
            return RedirectToAction("materialDefinations");
        }
        [HttpGet]
        public ActionResult newMaterialDefinition()
        {
            ViewBag.Status = new SelectList(Enum.GetValues(typeof(Status)));
            Material material = new Material();
            return View(material);
        }
        [HttpPost]
        public ActionResult newMaterialDefinition(Material material)
        {
            material.Save();
            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult newMaterial()
        {
            ViewBag.Status = new SelectList(Enum.GetValues(typeof(Status)));
            Material material = new Material();
            return View(material);
        }
        [HttpPost]
        public ActionResult newMaterial(Material material)
        {
            material.Save();
            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult deleteMaterialDefinition(int ID)
        {
            Material material = virames<Material>
                           .Initialize(new Material()).Where(x => x.ID.ToString() == ID.ToString())
                           .Take();
            return View(material);

        }
        [HttpPost]
        public ActionResult deleteMaterialDefinition(Material material)
        {
     
            material.Delete();
            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult detailMaterialFiche(int ID)
        {

            List<BOM> bomList = virames<BOM>.Initialize(new List<BOM>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
                           
            return View(bomList);
        }
        [HttpPost]
        public ActionResult detailMaterialFiche(BOM material)
        {
            
            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult detailCriteriaSet(int ID)
        {

            List<CriteriaSet> criteriaSetList = virames<CriteriaSet>.Initialize(new List<CriteriaSet>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();

            return View(criteriaSetList);
        }
        [HttpPost]
        public ActionResult detailCriteriaSet(CriteriaSet material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult detailDocumentManagement(int ID)
        {

            List<Document> materialDocumentList = virames<Document>.Initialize(new List<Document>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();

            return View(materialDocumentList);
        }
        [HttpPost]
        public ActionResult detailDocumentManagement(Document material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult detailDocument(int ID)
        {
            Document material = virames<Document>
                            .Initialize(new Document()).Where(x => x.ID.ToString() == ID.ToString())
                            .Take();
            return View(material);
        }
        [HttpPost]
        public ActionResult detailDocument(Document material)
        {
      
            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult detailDocumentRecord(int ID)
        {

            List<Material> criteriaSetList = virames<Material>.Initialize(new List<Material>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();

            return View(criteriaSetList);
        }
        [HttpPost]
        public ActionResult detailDocumentRecord(Material material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult receipts(int ID)
        {
         
            List<BOM> BOMList = virames<BOM>.Initialize(new List<BOM>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
            return View(BOMList);
        }
        [HttpPost]
        public ActionResult receipts(BOM material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult detailFiche(int ID)
        {

            List<MaterialFiche> ficheList = virames<MaterialFiche>.Initialize(new List<MaterialFiche>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
            return View(ficheList);
        }
        [HttpPost]
        public ActionResult detailFiche(MaterialFiche material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult detailEmployee(int ID)
        {

            List<Employee> employeeList = virames<Employee>.Initialize(new List<Employee>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
            return View(employeeList);
        }
        [HttpPost]
        public ActionResult detailEmployee(Employee material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult project(int ID)
        {

            List<Project> projectList = virames<Project>.Initialize(new List<Project>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
            return View(projectList);
        }
        [HttpPost]
        public ActionResult project(Project material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult productOrders(int ID)
        {

            List<ProductOrder> productOrderList = virames<ProductOrder>.Initialize(new List<ProductOrder>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
            return View(productOrderList);
        }
        [HttpPost]
        public ActionResult productOrders(ProductOrder material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult workStations(int ID)
        {

            List<Workstation> workstations = virames<Workstation>.Initialize(new List<Workstation>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
            return View(workstations);
        }
        [HttpPost]
        public ActionResult workStations(Workstation material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult purchaseContracts(int ID)
        {

            List<PurchaseContract> purchaseContractlList = virames<PurchaseContract>.Initialize(new List<PurchaseContract>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
            return View(purchaseContractlList);
        }
        [HttpPost]
        public ActionResult PurchaseContracts(PurchaseContract material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult purchaseIndents(int ID)
        {

            List<PurchaseIndent> purchaseIndentList = virames<PurchaseIndent>.Initialize(new List<PurchaseIndent>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
            return View(purchaseIndentList);
        }
        [HttpPost]
        public ActionResult purchaseIndents(PurchaseIndent material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult purchaseOrders(int ID)
        {

            List<PurchaseOrder> purchaseOrderList = virames<PurchaseOrder>.Initialize(new List<PurchaseOrder>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();
            return View(purchaseOrderList);
        }
        [HttpPost]
        public ActionResult purchaseOrders(PurchaseOrder material)
        {

            return RedirectToAction("materialDefinitions");
        }
        [HttpGet]
        public ActionResult purchaseProposal(int ID)
        {

            List<PurchaseProposal> purchaseProposalList = virames<PurchaseProposal>.Initialize(new List<PurchaseProposal>()).Where(x => x.ID.ToString() == ID.ToString()).GetList();

Views/ProductManagement/detailDocumentManagement.cshtml
@{
    ViewBag.Title = "detailDocumentManagement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using viramesV4.Object.BusinessLogicLayer.Master
@model IList<Document>

<section class="content-header">
   

    <div class="box-body">
        <a class="btn btn-app btn btn-primary" onclick="goBack()">
            <i class="fa fa-arrow-left"></i> Geri
        </a>
        <a class="btn btn-app " href="~/ProductManagement/materialDefinitions"> <span class=" fa fa-share-square"></span>Aktarım</a>
    </div>

</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <!-- /.box -->

            <div class="box">
                <div class="box-header">
                    <h2>
                       Malzeme Dökümanları

                    </h2>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Döküman No</th>
                                <th>Döküman Açıklaması</th>
                                <th>Proje</th>
                                <th>Aile No</th>
                                <th>Sayfa</th>
                                <th>Sayfa Sayısı</th>
                                <th>Revizyon</th>
                                <th>Geçerlilik</th>
                                <th>Durum</th>
                                <th>Departman Kapsamı</th>
                                <th>İşlem</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Document document in Model)
                            {

                            <tr>
                                <td>@document.DocumentNo</td>
                                <td>@document.Description</td>
                                <td>@document.Project</td>
                                <td>@document.FamilyNo</td>
                                <td>@document.Page</td>
                                <td>@document.PageCount</td>
                                <td>@document.Rev</td>
                                <td>@document.Availability</td>
                                <td>@document.Status </td>
                                <td>@document.DepartmentScope</td>
                                <td>
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Seç
                                        </button>
                                        <div class="dropdown-menu">
                                            <a  href="@Url.Action("detailDocument", "ProductManagement", new { id = document.ID })">
                                                <span class="fa fa-eye"> Görüntüle </span>
                                            </a>
                                            <a href="@Url.Action("detailMaterialFiche", "ProductManagement", new { id = document.ID })"><span class="fa fa-folder-open"> Dosya Aç </span></a>
                                        </div>

                                    </div>
                                     
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Dökümana Atanan Kayıtlar
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="@Url.Action("detailDocumentRecord", "ProductManagement", new { id = document.ID })"><span class="fa fa-eye"> Malzeme </span></a> <br />
                                            <a href="@Url.Action("receipts", "ProductManagement", new { id = document.ID })"><span class="fa fa-folder-open"> Reçeteler </span></a> <br />
                                            <a href="@Url.Action("detailFiche", "ProductManagement", new { id = document.ID })"><span class="fa fa-receipt"> Malzeme Fişleri </span></a> <br />
                                            <a href="@Url.Action("detailEmployee", "ProductManagement", new { id = document.ID })"><span class="fa fa-users"> Personeller </span></a> <br />
                                            <a href="@Url.Action("project", "ProductManagement", new { id = document.ID })"><span class="fa fa-files-o"> Projeler </span></a> <br />
                                            <a href="@Url.Action("productOrders", "ProductManagement", new { id = document.ID })"><span class="fa fa-files-o"> Üretim Emirleri </span></a> <br />
                                            <a href="@Url.Action("workStations", "ProductManagement", new { id = document.ID })"><span class="fa fa-files-o"> İş İstasyonları </span></a> <br />
                                            <a href="@Url.Action("purchaseContracts", "ProductManagement", new { id = document.ID })"><span class="fa fa-files-o"> Satınalma Sözleşmeleri </span></a> <br />
                                            <a href="@Url.Action("purchaseIndents", "ProductManagement", new { id = document.ID })"><span class="fa fa-files-o"> Satınalma Emirleri </span></a> <br />
                                            <a href="@Url.Action("purchaseOrders", "ProductManagement", new { id = document.ID })"><span class="fa fa-files-o"> Satınalma Siparişleri </span></a> <br />
                                            <a href="@Url.Action("purchaseProposal", "ProductManagement", new { id = document.ID })"><span class="fa fa-files-o"> Satınalma Teklifleri </span></a> <br />
                                            <a href="@Url.Action("certificates", "ProductManagement", new { id = document.ID })"><span class="fa fa-files-o"> Sertifikalar </span></a> <br />
                                        </div>

                                    </div>
                                </td>
                            </tr>

                            }
                        </tbody>

                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

Views/ProductManagement/detailDocumentRecord.cshtml
@{
    ViewBag.Title = "detailDocumentRecord";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using viramesV4.Object.BusinessLogicLayer.Master
@model IList<Material>

<section class="content-header">

    <div class="box-body ">
        <a class="btn btn-app btn btn-primary" onclick="goBack()">
            <i class="fa fa-arrow-left"></i> Geri
        </a>
    </div>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <!-- /.box -->

            <div class="box">
                <div class="box-header">
                    <h2>
                        Dökümana Atanan Kayıtlar

                    </h2>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Malzeme Kodu ve Tanımı</th>
                                <th>Malzeme Türü</th>
                                <th>Birim Seti</th>
                                <th>Raf Konumu</th>
                                <th>Varsayılan Depo</th>
                                <th>İzleme Türü</th>
                                <th>Malzeme Durumu</th>
                                <th>Fiyatı</th>
                                <th>Miktarı</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Material material in Model)
                            {

                                <tr>
                                    <td>@material.CodeAndDefinition</td>
                                    <td>@material.MaterialType</td>
                                    <td>@material.UnitSet</td>
                                    <td>@material.ShelfLocation</td>
                                    <td>@material.DefaultWarehouse</td>
                                    <td>@material.TraceType</td>
                                    <td>@material.Status</td>
                                    <td>@material.Price</td>
                                    <td>@material.OnHand</td>


                                </tr>

                            }
                        </tbody>

                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

Views/ProductManagement/engineeringOperations.cshtml
@{
    ViewBag.Title = "engineeringOperations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using viramesV4.Object.BusinessLogicLayer.Master
@model IList<Material>


<section class="content-header">

    <div class="box-body">
        <a class="btn btn-app btn btn-primary" href="~/ProductManagement/newMaterialDefinition">
            <i class="fa fa-file"></i> Yeni
        </a>
        <a class="btn btn-app">
            <i class="fa fa-share-square" data-toggle="modal" data-target="#ModalButton"></i> Aktarım
        </a>
        <div class="modal fade" id="ModalButton" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h3>Dışa Aktar</h3>
                    </div>
                    <div class="modal-body">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                            <label class="form-check-label" for="inlineRadio1">Text File (.txt)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                            <label class="form-check-label" for="inlineRadio2">Excel File (.xlsx)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                            <label class="form-check-label" for="inlineRadio1">Html File (.txt)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="option4">
                            <label class="form-check-label" for="inlineRadio2">PDF File (.pdf)</label>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Aktar</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Kapat</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <!-- /.box -->

            <div class="box">
                <div class="box-header">
                    <h2>
                        Malzeme Kartları

                    </h2>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Malzeme Türü Tanımı</th>
                                <th>Malzeme Kodu</th>
                                <th>Malzeme Tanımı</th>
                                <th>Miktarı</th>
                                <th>Ana Birim</th>
                                <th>Malzeme Özelliği</th>
                                <th>İzleme Türü</th>
                                <th>Özel Kod</th>
                                <th>Malzeme Durumu</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Material material in Model)
                            {

                                <tr>
                                    <td>@material.MaterialType.Definition</td>
                                    <td>@material.Code</td>
                                    <td>@material.Definition</td>
                                    <td>@material.OnHand</td>
                                    <td>@material.MainUnit</td>
                                    <td>@material.MaterialSpecification</td>
                                    <td>@material.TraceType</td>
                                    <td>@material.SpeCode</td>
                                    <td>@material.Status</td>
                                    <td>
                                        <div class="dropdown btn-group dropleft">
                                            <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                                Seç
                                            </button>
                                            <div class="dropdown-menu">
                                                <a href="@Url.Action("detailMaterialDefinition", "ProductManagement", new { id = material.ID })"><span class="fa fa-eye"> Görüntüle </span></a> <br />
                                                <a href="@Url.Action("editMaterialDefinition", "ProductManagement", new { id = material.ID })"><span class="fa fa-edit"> Düzenle </span></a> <br />
                                                <a href="@Url.Action("detailMaterialFiche", "ProductManagement", new { id = material.ID })"><span class="fa fa-receipt"> Reçete Listesi </span></a> <br />
                                                <a href="@Url.Action("detailCriteriaSet", "ProductManagement", new { id = material.ID })"><span class="fa fa-tasks"> Kriter Setleri </span></a> <br />
                                                <a href="@Url.Action("detailDocumentManagement", "ProductManagement", new { id = material.ID })"><span class="fa fa-sitemap"> Döküman Yönetimi </span></a> <br />
                                                <a href="@Url.Action("deleteMaterialDefinition", "ProductManagement", new { id = material.ID })"><span class="fa fa-trash"> Sil </span></a> <br />

                                            </div>

                                        </div>
                                    </td>
                                </tr>

                            }
                        </tbody>

                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

Views/ProductManagement/materialCriteriaSetAppointments.cshtml
@{
    ViewBag.Title = "materialCriteriaSetAppointments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using viramesV4.Object.BusinessLogicLayer.Master
@model IList<MaterialCriteriaSetAppointment>


<section class="content-header">
    <h1>
        Malzeme Kriter Seti Atamaları

    </h1>

    <div class="box-body">
        <a href="http://virames.cloud/ProductManagement/newMaterialCriteriaSetAppointments" class="btn btn-app btn btn-primary">
            
            <i class="fa fa-file"></i> Yeni
        </a>
        <a class="btn btn-app">
            <i class="fa fa-share-square"></i> Aktarım
        </a>
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">

        <div class="col-xs-12">



            <!-- /.box -->

            <div class="box">
                <div class="box-header">
                    <h2>
                        Malzeme Kriter Seti Atamaları

                    </h2>

                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Malzeme</th>
                                <th>Kriter Seti</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (MaterialCriteriaSetAppointment materialCriteriaSetAppointment in Model)
                            {

                            <tr>
                                <td>@materialCriteriaSetAppointment.Material</td>
                                <td>@materialCriteriaSetAppointment.CriteriaSet</td>
                                <td>
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Seç
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="@Url.Action("detailMaterialCriteriaSetAppointments", "ProductManagement", new { id = materialCriteriaSetAppointment.ID })"><span class="fa fa-eye"> Görüntüle </span></a> <br />
                                            <a href="@Url.Action("editMaterialCriteriaSetAppointments", "ProductManagement", new { id = materialCriteriaSetAppointment.ID })"><span class="fa fa-edit"> Düzenle </span> </a><br />
                                            @*<a href="@Url.Action("detailMaterialFiche", "ProductManagement", new { id = material.ID })"></a>*@<span class="fa fa-receipt"> Reçete Listesi </span> <br />
                                            @*<a href="@Url.Action("detailCriteriaSet", "ProductManagement", new { id = material.ID })"></a>*@<span class="fa fa-tasks"> Kriter Setleri </span> <br />
                                            @*<a href="@Url.Action("detailDocumentManagement", "ProductManagement", new { id = material.ID })"></a>*@<span class="fa fa-sitemap"> Döküman Yönetimi </span> <br />
                                            @*<a href="@Url.Action("deleteFicheMaterial", "ProductManagement", new { id = materialfiche.ID })"><span class="fa fa-trash"> Sil </span></a> <br />*@*@*@*@

                                        </div>

                                    </div>
                                </td>
                            </tr>

                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>