Controllers/SystemManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using viramesV4.Cloud.Helpers;
using viramesV4.Object.BusinessLogicLayer.Master;
using viramesV4.Object.BusinessLogicLayer.System;
using viramesV4.Object.Factory;
using viramesV4.Object.HelperLayer;
using Log = viramesV4.Object.BusinessLogicLayer.System.Log;

namespace viramesV4.Cloud.Controllers
{
    [ViramesAuthorization]
    public class SystemManagementController : Controller
    {

        #region Master Records

        #region Role
        [HttpGet]
        public ActionResult Role()
        {
            ViewBag.Isactive = 80;
            List<Role> roleList = virames<Role>
                             .Initialize(new List<Role>())
                             .GetList();
            return View(roleList);
        }
        [HttpGet]
        public ActionResult NewRole()
        {
            ViewBag.UserType = new SelectList(Enum.GetValues(typeof(UserType)));
            Role role = new Role();
            return View(role);
        }
        [HttpPost]
        public ActionResult NewRole(Role role)
        {
            role.Save();
            return RedirectToAction("Role");
        }
        [HttpGet]
        public ActionResult EditRole(int ID)
        {
            ViewBag.UserType = new SelectList(Enum.GetValues(typeof(UserType)));
            Role role = virames<Role>
                             .Initialize(new Role()).Where(x => x.ID.ToString() == ID.ToString())
                             .Take();
            return View(role);
        }
        [HttpPost]
        public ActionResult EditRole(Role role)
        {
            role.Save();
            return RedirectToAction("Role");
        }
        [HttpGet]
        public ActionResult DetailRole(int ID)
        {
            Role role = virames<Role>
                            .Initialize(new Role()).Where(x => x.ID.ToString() == ID.ToString())
                            .Take();
            return View(role);
        }
        [HttpPost]
        public ActionResult DetailRole(Role role)
        {
            role.Save();
            return RedirectToAction("Role");
        }
        [HttpGet]
        public ActionResult DeleteRole(int ID)
        {
            Role role = virames<Role>
                           .Initialize(new Role()).Where(x => x.ID.ToString() == ID.ToString())
                           .Take();
            return View(role);

        }
        [HttpPost]
        public ActionResult DeleteRole(Role role)
        {
            role.Delete();
            return RedirectToAction("Role");
        }
        #endregion

        #region User
        [HttpGet]
        public new ActionResult User()
        {
            ViewBag.Isactive = 81;
            List<User> usrList = virames<User>
                            .Initialize(new List<User>())
                            .GetList();
            return View(usrList);
        }
        [HttpGet]
        public ActionResult NewUser()
        {
            ViewBag.User = virames<Role>.Initialize(new List<Role>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.Name + " | " + x.UserType
            });
            User user = new User();
            return View(user);
        }
        [HttpPost]
        public ActionResult NewUser(User user)
        {
            user.Save();
            return RedirectToAction("User");
        }
        [HttpGet]
        public ActionResult EditUser(int ID)
        {
            ViewBag.User = virames<Role>.Initialize(new List<Role>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.Name + " | " + x.UserType
            });
            User user = virames<User>
                             .Initialize(new User()).Where(x => x.ID.ToString() == ID.ToString())
                             .Take();
            return View(user);
        }
        [HttpPost]
        public ActionResult EditUser(User user)
        {
            user.Save();
            return RedirectToAction("User");
        }
        [HttpGet]
        public ActionResult DetailUser(int ID)
        {
            User user = virames<User>
                            .Initialize(new User()).Where(x => x.ID.ToString() == ID.ToString())
                            .Take();
            return View(user);
        }
        [HttpPost]
        public ActionResult DetailUser(User user)
        {
            user.Save();
            return RedirectToAction("User");
        }
        [HttpGet]
        public ActionResult DeleteUser(int ID)
        {
            User user = virames<User>
                           .Initialize(new User()).Where(x => x.ID.ToString() == ID.ToString())
                           .Take();
            return View(user);

        }
        [HttpPost]
        public ActionResult DeleteUser(User user)
        {
            user.Delete();
            return RedirectToAction("User");
        }
        [HttpGet]
        public ActionResult EditPassword(int ID)
        {
            User user = virames<User>
                               .Initialize(new User()).Where(x => x.ID.ToString() == ID.ToString())
                               .Take();
            return View(user);
        }
        [HttpPost]
        public ActionResult SetEditPassword(int Id)
        {

            User user = virames<User>
                               .Initialize(new User()).Where(x => x.ID.ToString() == Id.ToString())
                               .Take();
            user.Password = Functions.MD5(Session["NewPassword"].ToString());
            user.Save();
            return RedirectToAction("User");
        }
        #endregion

        #region WorkArea
        [HttpGet]
        public ActionResult WorkArea()
        {
            ViewBag.Isactive = 82;
            List<Workarea> waList = virames<Workarea>
                             .Initialize(new List<Workarea>())
                             .GetList();
            return View(waList);
        }
        [HttpGet]
        public ActionResult NewWorkArea()
        {
            ViewBag.Status = new SelectList(Enum.GetValues(typeof(Status)));
            ViewBag.Currency = virames<Workarea>
                          .Initialize(new List<Workarea>())
                          .GetList().Select(x => new SelectListItem
                          {
                              Value = x.ID.ToString(),
                              Text = x.Currency.Name + " | " + x.Currency.Symbol
                          });
            Workarea workarea = new Workarea();
            return View(workarea);
        }
        [HttpPost]
        public ActionResult NewWorkArea(Workarea workarea)
        {
            workarea.Save();
            return RedirectToAction("WorkArea");
        }
        [HttpGet]
        public ActionResult EditWorkArea(int ID)
        {
            ViewBag.Status = new SelectList(Enum.GetValues(typeof(Status)));
            ViewBag.Currency = virames<Workarea>.Initialize(new List<Workarea>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.Currency.Name + " | " + x.Currency.Symbol
            });
            Workarea workarea = virames<Workarea>
                             .Initialize(new Workarea()).Where(x => x.ID.ToString() == ID.ToString())
                             .Take();
            return View(workarea);
        }
        [HttpPost]
        public ActionResult EditWorkArea(Workarea workarea)
        {
            workarea.Save();
            return RedirectToAction("WorkArea");
        }
        [HttpGet]
        public ActionResult DeleteWorkArea(int ID)
        {
            Workarea workarea = virames<Workarea>
                           .Initialize(new Workarea()).Where(x => x.ID.ToString() == ID.ToString())
                           .Take();
            return View(workarea);

        }
        [HttpPost]
        public ActionResult DeleteWorkArea(Workarea workarea)
        {
            workarea.Delete();
            return RedirectToAction("WorkArea");
        }
        #endregion

        #region Terminal
        [HttpGet]
        public ActionResult Terminal()
        {
            ViewBag.Isactive = 83;
            List<Terminal> terminal = virames<Terminal>
                             .Initialize(new List<Terminal>())
                             .GetList();
            return View(terminal);
        }
        [HttpGet]
        public ActionResult NewTerminal()
        {
            ViewBag.User = virames<User>.Initialize(new List<User>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.Username + " | " + x.Name + " | " + x.Role + " | " + x.Password
            });
            Terminal terminal = new Terminal();
            return View(terminal);
        }
        [HttpPost]
        public ActionResult NewTerminal(Terminal terminal)
        {
            terminal.Save();
            return RedirectToAction("Terminal");
        }
        [HttpGet]
        public ActionResult EditTerminal(int ID)
        {
            ViewBag.User = virames<User>.Initialize(new List<User>()).GetList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.Username + " | " + x.Name + " | " + x.Role + " | " + x.Password
            });
            Terminal terminal = virames<Terminal>
                             .Initialize(new Terminal()).Where(x => x.ID.ToString() == ID.ToString())
                             .Take();
            return View(terminal);
        }
        [HttpPost]
        public ActionResult EditTerminal(Terminal terminal)
        {
            terminal.Save();
            return RedirectToAction("Terminal");
        }
        [HttpGet]

Views/SystemManagement/DeleteTerminal.cshtml
@model viramesV4.Object.BusinessLogicLayer.System.Terminal

@{
    ViewBag.Title = "DeleteTerminal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <section class="content-header">
        <h3>Çalışma Alanı Tanımları</h3>
        <div class="box-body ">
            <a class="btn btn-app btn btn-primary" onclick="goBack()">
                <i class="fa fa-arrow-left"></i> Geri
            </a>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Sil</h3>
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.TerminalCode)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.TerminalCode)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Name)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Name)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CreatedBy)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CreatedBy)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.CreatedDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CreatedDate)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ModifiedBy)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ModifiedBy)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.ModifiedDate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ModifiedDate)
                                </dd>

                            </dl>
                        </div>
                        <br />
                        <div class="form-actions col-xs-2">
                            <input type="submit" value="Sil" class="btn btn-app btn btn-primary" />
                        </div>
                        <br />
                        <br />
                        <br />
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </section>

}

Views/SystemManagement/DetailRole.cshtml
@model viramesV4.Object.BusinessLogicLayer.System.Role

@{
    ViewBag.Title = "DetailRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <section class="content-header">
        <h3>Rol Tanımları</h3>
        <div class="box-body ">
            <a class="btn btn-app btn btn-primary" onclick="goBack()">
                <i class="fa fa-arrow-left"></i> Geri
            </a>
            <a class="btn btn-app btn btn-primary" href="~/SystemManagement/EditRole/@Model.ID">
                <i class="fa fa-edit"></i> Düzenle
            </a>
        </div>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Görüntüle</h3>
                    </div>
                    <div class="box-body">
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.CreatedBy)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.CreatedBy)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.CreatedDate)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.CreatedDate)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ModifiedBy)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ModifiedBy)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ModifiedDate)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ModifiedDate)
                            </dd>

                        </dl>
                        <br />
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </section>
}

Views/SystemManagement/LayOut.cshtml
@using viramesV4.Object.BusinessLogicLayer.System
@model IList<Layout>
@{
    ViewBag.Title = "layOut";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
        Layout Tasarımları
    </h1>
    <div class="box-body ">
        <button type="button" class="btn btn-primary">
            <span class=" fa fa-share-square"></span> Aktarım
        </button>
        <button type="button" class="btn btn-danger">
            <span class=" fa fa-trash"></span> Sil
        </button>
    </div>


</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Kullanıcı</th>
                                <th>İsim</th>
                                <th>Açıklama</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Layout layoutt in Model)
                            {
                                <tr>
                                    <td>@layoutt.User</td>
                                    <td>@layoutt.Name</td>
                                    <td>@layoutt.Definition</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

Views/SystemManagement/Terminal.cshtml
@using viramesV4.Object.BusinessLogicLayer.System
@model IList<Terminal>
@{
    ViewBag.Title = "terminal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h3>Terminal Tanımları</h3>
    <div class="box-body">
        <a class="btn btn-app btn btn-primary" href="~/SystemManagement/NewTerminal">
            <i class="fa fa-file"></i> Yeni
        </a>
        <a class="btn btn-app">
            <i class="fa fa-share-square" data-toggle="modal" data-target="#ModalButton"></i> Aktarım
        </a>
        <div class="modal fade" id="ModalButton" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h3>Dışa Aktar</h3>
                    </div>
                    <div class="modal-body">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                            <label class="form-check-label" for="inlineRadio1">Text File (.txt)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                            <label class="form-check-label" for="inlineRadio2">Excel File (.xlsx)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                            <label class="form-check-label" for="inlineRadio1">Html File (.txt)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="option4">
                            <label class="form-check-label" for="inlineRadio2">PDF File (.pdf)</label>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Aktar</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Kapat</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Terminal Kodu</th>
                                <th>Terminal Adı</th>
                                <th>Kullanıcı Adı</th>
                                <th>Seçim</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Terminal terminal in Model)
                            {
                            <tr>
                                <td>@terminal.TerminalCode</td>
                                <td>@terminal.Name</td>
                                <td>@terminal.User</td>
                                <td>
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Seç
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="@Url.Action("DetailTerminal", "SystemManagement", new { id = terminal.ID })"><span class="fa fa-eye"> Görüntüle </span></a> <br />
                                            <a href="@Url.Action("EditTerminal", "SystemManagement", new { id = terminal.ID })"><span class="fa fa-edit"> Düzenle </span></a> <br />
                                            <a href="@Url.Action("DeleteTerminal", "SystemManagement", new { id = terminal.ID })"><span class="fa fa-trash"> Sil </span></a> <br />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

Views/SystemManagement/User.cshtml
@using viramesV4.Object.BusinessLogicLayer.System
@model IList<User>
@{
    ViewBag.Title = "user";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h3>Kullanıcı Tanımları</h3>
    <div class="box-body">
        <a class="btn btn-app btn btn-primary" href="~/SystemManagement/NewUser">
            <i class="fa fa-file"></i> Yeni
        </a>
        <a class="btn btn-app">
            <i class="fa fa-share-square" data-toggle="modal" data-target="#ModalButton"></i> Aktarım
        </a>
        <div class="modal fade" id="ModalButton" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h3>Dışa Aktar</h3>
                    </div>
                    <div class="modal-body">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                            <label class="form-check-label" for="inlineRadio1">Text File (.txt)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                            <label class="form-check-label" for="inlineRadio2">Excel File (.xlsx)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                            <label class="form-check-label" for="inlineRadio1">Html File (.txt)</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio4" value="option4">
                            <label class="form-check-label" for="inlineRadio2">PDF File (.pdf)</label>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Aktar</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Kapat</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Kullanıcı Adı</th>
                                <th>İsim Soyisim</th>
                                <th>Kullanıcı Rolü</th>
                                <th>Seçim</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (User user in Model)
                            {
                            <tr>
                                <td>@user.Username</td>
                                <td>@user.Name</td>
                                <td>@user.Role</td>
                                <td>
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Seç
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="@Url.Action("DetailUser", "SystemManagement", new { id = user.ID })"><span class="fa fa-eye"> Görüntüle </span></a> <br />
                                            <a href="@Url.Action("EditUser", "SystemManagement", new { id = user.ID })"><span class="fa fa-edit"> Düzenle </span></a> <br />
                                            <a href="@Url.Action("DeleteUser", "SystemManagement", new { id = user.ID })"><span class="fa fa-trash"> Sil </span></a> <br />
                                            <a href="@Url.Action("EditPassword", "SystemManagement", new { id = user.ID })"><span class="fa fa-key"> Şifre Değiştir </span></a> <br />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

Views/SystemManagement/WorkArea.cshtml
@using viramesV4.Object.BusinessLogicLayer.System
@model IList<Workarea>
@{
    ViewBag.Title = "workArea";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h3>Rol Tanımları</h3>
    <div class="box-body">
        <a class="btn btn-app btn btn-primary" href="~/SystemManagement/NewWorkArea">
            <i class="fa fa-file"></i> Yeni
        </a>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Çalışma Alanı Kodu</th>
                                <th>Çalışma Alanı Adı</th>
                                <th>Durum</th>
                                <th>Başlangıç Tarihi</th>
                                <th>Bitiş Tarihi</th>
                                <th>Majör</th>
                                <th>Minör</th>
                                <th>Patch</th>
                                <th>Veri Tabanı Türü</th>
                                <th>Seçim</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Workarea workarea in Model)
                            {
                            <tr>
                                <td>@workarea.Code</td>
                                <td>@workarea.Name</td>
                                <td>@workarea.Status</td>
                                <td>@workarea.StartDate</td>
                                <td>@workarea.EndDate</td>
                                <td>@workarea.Major</td>
                                <td>@workarea.Minor</td>
                                <td>@workarea.Patch</td>
                                <td>@workarea.DatabaseType</td>
                                <td>
                                    <div class="dropdown btn-group dropleft">
                                        <button class="btn  btn-primary dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown">
                                            Seç
                                        </button>
                                        <div class="dropdown-menu">
                                            <a href="@Url.Action("EditWorkArea", "SystemManagement", new { id = workarea.ID })"><span class="fa fa-edit"> Düzenle </span></a> <br />
                                            <a href="@Url.Action("DeleteWorkArea", "SystemManagement", new { id = workarea.ID })"><span class="fa fa-trash"> Sil </span></a> <br />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>